### PR TITLE
Add compatibility with errors-2.0.*, resolves #33

### LINKED ISSUE #33: Please add support for recent versions of errors
After updating NixOS to errors 2.x, we can no longer built your package: http://packdeps.haskellers.com/feed?needle=octohat.

### PR DESCRIPTION
**Pull request by juanpaucar**
@jsl @jsantos17 Could you take a look, please?

### CODE REVIEW

**Comment by juanpaucar** [comment]
@jsl could you turn off circleCI tests, please? We didn't put the tokens needed for the tests so they are likely to fail and we already have TravisCI running tests too

**Comment by jsantos17** [comment]
LGTM. CPP is always ugly, but seems like a fairly good solution here.

**Comment by juanpaucar** [comment]
For the record. I'm merging it now with circleCI tests failing because the tokens needed for the tests are not set. On the other hand we only need travisCI tests passing, since the are authentication tokens are properly set.

**Comment by jsl** [comment]
Just curious, any way that we could do something like [this](https://github.com/stackbuilders/parseerror-eq) to release to a separate library? @juanpaucar

**Pull request merged**
