### PR TITLE
Add GHC 7.10 support

### PR DESCRIPTION
**Pull request by sestrella**

### CODE REVIEW

**Comment by sestrella** [comment]
@jsantos17 @jsl @juanpaucar could you guys take a look please

**Comment by juanpaucar** [comment]
@sestrella LGTM. the only bad part is that now will have to wait for 4 containers to finish on CI but it is actually better to have it better tested

**Comment by sestrella** [comment]
seems that one of the external dependencies `wreq` is broken https://github.com/bos/wreq/pull/64

**Comment by jsl** [comment]
LGTM

**Pull request merged**
